title: Man in the Arena (or woman!)
author: Christine
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  A great speech and quote.
# social links
twitter_username: your-twitter-handle
github_username:  your-github-handle

show_excerpts: true # set to false to remove excerpts on the homepage

theme: jekyll-theme-minimal
